# Generated by Django 3.1.5 on 2021-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_person_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
